### ISSUE TITLE
better logo

### ISSUE THREAD

**Issue by kingluddite** [reguv760/gatsby-storeytime#74]
Their current logo is not great
I think a music note and a book?
We could use something like this to save time: https://websitesetup.org/15-best-online-logo-generators/

also there is a logo that is temp in : https://websitesetup.org/15-best-online-logo-generators/ this is for SEO, when we update the logo we need to also update this

src/assets/images/logos/300x300-ics-logo.png

**Comment by reguv760** [comment]
think I'm going to redraw the logo I create in one of these online logo generators in Illustrator; not too happy with the font selection in some of them (I have a whole library of them). If the client really likes the logo, then I can provide vector files.

**Comment by reguv760** [comment]
was playing around with fonts and came up with something that has a similar feel from the original logo while integrating musical notations as a graphic element. The "S" can be used for the favicon. As for colors, tried to use the same blue used on the site but probably need something darker/bolder. Logos are not final and probably needs a few tweaks. 

![storeytime-logos](https://user-images.githubusercontent.com/30225349/57234908-91b8c280-6fd6-11e9-818d-6dbc0edfb2d8.jpg)

**Comment by kingluddite** [comment]
I like it. Let's use it. First one works.  And it gives us our primary
brand color. Nice work!

**Comment by reguv760** [comment]
sweet.... just updated the master with the logo and updated the accent1 color
