### ISSUE TITLE
Fix Home Page heading spacing

### ISSUE THREAD

**Issue by kingluddite** [reguv760/gatsby-storeytime#82]
The About Us needs to be pushed down on the page

**Comment by reguv760** [comment]
are ya pertaining to the component that's holding the current "About us" content?

**Comment by kingluddite** [comment]
yes. Let's change "About Us" to "Storeytime" and underneath the long border separate let's put the tag line "Creating Possibility Through Music"

**Comment by reguv760** [comment]
padding applied to section in _vars.scss... this also resolves issue #80
